# Generated by Django 5.2 on 2025-06-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('music_file', models.FileField(upload_to='music/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
