# Generated by Django 5.2 on 2025-06-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
